//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXClientSimulator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FXClientSimulator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Close.
        /// </summary>
        public static string ApplicationSettings_ConfirmClose {
            get {
                return ResourceManager.GetString("ApplicationSettings_ConfirmClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Port.
        /// </summary>
        public static string ApplicationSettings_InvalidPort {
            get {
                return ResourceManager.GetString("ApplicationSettings_InvalidPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid port number between 0 and 65535.
        /// </summary>
        public static string ApplicationSettings_PortNumbersHelp {
            get {
                return ResourceManager.GetString("ApplicationSettings_PortNumbersHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection settings have changed, do you want to save them?.
        /// </summary>
        public static string ApplicationSettings_SaveConnectionSettings {
            get {
                return ResourceManager.GetString("ApplicationSettings_SaveConnectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Price.
        /// </summary>
        public static string AutoQuoteNewOrder_InvalidPrice {
            get {
                return ResourceManager.GetString("AutoQuoteNewOrder_InvalidPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Quantity.
        /// </summary>
        public static string AutoQuoteNewOrder_InvalidQuantity {
            get {
                return ResourceManager.GetString("AutoQuoteNewOrder_InvalidQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders from quoted prices must have a Quote Id.
        /// </summary>
        public static string AutoQuoteNewOrder_InvalidQuoteId {
            get {
                return ResourceManager.GetString("AutoQuoteNewOrder_InvalidQuoteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot determine buy or sell order.
        /// </summary>
        public static string AutoQuoteNewOrder_InvalidSide {
            get {
                return ResourceManager.GetString("AutoQuoteNewOrder_InvalidSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create an order for an unknown symbol.
        /// </summary>
        public static string AutoQuoteNewOrder_UnknownSymbol {
            get {
                return ResourceManager.GetString("AutoQuoteNewOrder_UnknownSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate order details.
        /// </summary>
        public static string AutoQuoteNewOrder_ValidateOrderDetails {
            get {
                return ResourceManager.GetString("AutoQuoteNewOrder_ValidateOrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action interupted.
        /// </summary>
        public static string SysMsg_ActionInterupted {
            get {
                return ResourceManager.GetString("SysMsg_ActionInterupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error the number you have entered is not a valid amount.
        /// </summary>
        public static string SysMsg_InvalidAmount {
            get {
                return ResourceManager.GetString("SysMsg_InvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Invalid Input.
        /// </summary>
        public static string SysTitle_InvalidInput {
            get {
                return ResourceManager.GetString("SysTitle_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIX Server connected.
        /// </summary>
        public static string toolStrip_FIXConnected {
            get {
                return ResourceManager.GetString("toolStrip_FIXConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to FIX Server, please wait....
        /// </summary>
        public static string toolStrip_FIXConnecting {
            get {
                return ResourceManager.GetString("toolStrip_FIXConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIX Server disconnected.
        /// </summary>
        public static string toolStrip_FIXDisconnected {
            get {
                return ResourceManager.GetString("toolStrip_FIXDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting from FIX Server, please wait....
        /// </summary>
        public static string toolStrip_FIXDisconnecting {
            get {
                return ResourceManager.GetString("toolStrip_FIXDisconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Data FIX Transport is not connected - you must connect to the server before you can submit an order..
        /// </summary>
        public static string toolStrip_MDNotConnected_Orders {
            get {
                return ResourceManager.GetString("toolStrip_MDNotConnected_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Data FIX Transport is not connected - you must connect to the server before you can subscribe for pricing..
        /// </summary>
        public static string toolStrip_MDNotConnected_Pricing {
            get {
                return ResourceManager.GetString("toolStrip_MDNotConnected_Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote FIX Transport is not connected to the Server - you must connect to the server before you can send a quote request..
        /// </summary>
        public static string toolStrip_RFQNotConnected_Quotes {
            get {
                return ResourceManager.GetString("toolStrip_RFQNotConnected_Quotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade FIX Transport is not connected to the Server - you must connect to the server before you can submit an order..
        /// </summary>
        public static string toolStrip_TDNotConnected_Orders {
            get {
                return ResourceManager.GetString("toolStrip_TDNotConnected_Orders", resourceCulture);
            }
        }
    }
}
