//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXClientSimulator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string FIXHostMD {
            get {
                return ((string)(this["FIXHostMD"]));
            }
            set {
                this["FIXHostMD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14045")]
        public int FIXPortMD {
            get {
                return ((int)(this["FIXPortMD"]));
            }
            set {
                this["FIXPortMD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CL1")]
        public string SenderIdMD {
            get {
                return ((string)(this["SenderIdMD"]));
            }
            set {
                this["SenderIdMD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("APAMA_ECOM_RATES")]
        public string TargetIdMD {
            get {
                return ((string)(this["TargetIdMD"]));
            }
            set {
                this["TargetIdMD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string FIXHostTD {
            get {
                return ((string)(this["FIXHostTD"]));
            }
            set {
                this["FIXHostTD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14040")]
        public int FIXPortTD {
            get {
                return ((int)(this["FIXPortTD"]));
            }
            set {
                this["FIXPortTD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CL1")]
        public string SenderIdTD {
            get {
                return ((string)(this["SenderIdTD"]));
            }
            set {
                this["SenderIdTD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("APAMA_ECOM_ORDERS")]
        public string TargetIdTD {
            get {
                return ((string)(this["TargetIdTD"]));
            }
            set {
                this["TargetIdTD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string FIXHostRFQ {
            get {
                return ((string)(this["FIXHostRFQ"]));
            }
            set {
                this["FIXHostRFQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14050")]
        public int FIXPortRFQ {
            get {
                return ((int)(this["FIXPortRFQ"]));
            }
            set {
                this["FIXPortRFQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CL1")]
        public string SenderIdRFQ {
            get {
                return ((string)(this["SenderIdRFQ"]));
            }
            set {
                this["SenderIdRFQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("APAMA_ECOM_RFQ")]
        public string TargetIdRFQ {
            get {
                return ((string)(this["TargetIdRFQ"]));
            }
            set {
                this["TargetIdRFQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string EncryptionMethodMD {
            get {
                return ((string)(this["EncryptionMethodMD"]));
            }
            set {
                this["EncryptionMethodMD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int HeartbeatIntervalMD {
            get {
                return ((int)(this["HeartbeatIntervalMD"]));
            }
            set {
                this["HeartbeatIntervalMD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ResetSequenceNumberMD {
            get {
                return ((bool)(this["ResetSequenceNumberMD"]));
            }
            set {
                this["ResetSequenceNumberMD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string EncryptionMethodTD {
            get {
                return ((string)(this["EncryptionMethodTD"]));
            }
            set {
                this["EncryptionMethodTD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int HeartbeatIntervalTD {
            get {
                return ((int)(this["HeartbeatIntervalTD"]));
            }
            set {
                this["HeartbeatIntervalTD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ResetSequenceNumberTD {
            get {
                return ((bool)(this["ResetSequenceNumberTD"]));
            }
            set {
                this["ResetSequenceNumberTD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string EncryptionMethodRFQ {
            get {
                return ((string)(this["EncryptionMethodRFQ"]));
            }
            set {
                this["EncryptionMethodRFQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int HeartbeatIntervalRFQ {
            get {
                return ((int)(this["HeartbeatIntervalRFQ"]));
            }
            set {
                this["HeartbeatIntervalRFQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ResetSequenceNumberRFQ {
            get {
                return ((bool)(this["ResetSequenceNumberRFQ"]));
            }
            set {
                this["ResetSequenceNumberRFQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("marketDataLog.log")]
        public string MDLogPath {
            get {
                return ((string)(this["MDLogPath"]));
            }
            set {
                this["MDLogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tradeDataLog.log")]
        public string TDLogPath {
            get {
                return ((string)(this["TDLogPath"]));
            }
            set {
                this["TDLogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rfqDataLog.log")]
        public string RFQLogPath {
            get {
                return ((string)(this["RFQLogPath"]));
            }
            set {
                this["RFQLogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FXAGG")]
        public string DefaultAccount {
            get {
                return ((string)(this["DefaultAccount"]));
            }
            set {
                this["DefaultAccount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoConnect {
            get {
                return ((bool)(this["AutoConnect"]));
            }
            set {
                this["AutoConnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OnBehalfOf {
            get {
                return ((string)(this["OnBehalfOf"]));
            }
            set {
                this["OnBehalfOf"] = value;
            }
        }
    }
}
